package ntt

// This file was auto-generated by goenum.exe
// Do not modify this file directly.
// The name of the original description file used to generate this one is ./goenum/SizeStatus.goenum
// The name of the template is ./goenum/goenum.template

import (
	"errors"
	"strings"
)

type SizeStatus int

const (
	SizeStatusCount = 3
	SizeStatusMaxIndex = int(SizeStatusMinimized)
	SizeStatusLastValue = SizeStatusMinimized
)

const (
	SizeStatusNormal SizeStatus = iota
	SizeStatusMaximized
	SizeStatusMinimized
)

func (v SizeStatus) String() string {
	return [...]string{
		"SizeStatusNormal",
		"SizeStatusMaximized",
		"SizeStatusMinimized",
	}[v]
}

func SizeStatusFromString(s string) (SizeStatus, error) {
	var suffix string
	if strings.HasPrefix(s, "SizeStatus") {
		l := len("SizeStatus")
		if l < len(s) {
			suffix = s[l:]
		}
	} else {
		suffix = s
	}
	switch suffix {
	case "Normal":
		return SizeStatusNormal, nil
	case "Maximized":
		return SizeStatusMaximized, nil
	case "Minimized":
		return SizeStatusMinimized, nil
	}
	return SizeStatus(0), errors.New("String does not correspond to any existing SizeStatus values")
}
