package engine

// This file was auto-generated by goenum.exe
// Do not modify this file directly.
// The name of the original description file used to generate this one is ./goenum/Direction.goenum
// The name of the template is ./goenum/goenum.template

import (
	"errors"
	"strings"
)

type Direction int

const (
	DirectionCount = 2
	DirectionMaxIndex = int(DirectionBackward)
	DirectionLastValue = DirectionBackward
)

const (
	DirectionForward Direction = iota
	DirectionBackward
)

func (v Direction) String() string {
	return [...]string{
		"DirectionForward",
		"DirectionBackward",
	}[v]
}

func DirectionFromString(s string) (Direction, error) {
	var suffix string
	if strings.HasPrefix(s, "Direction") {
		l := len("Direction")
		if l < len(s) {
			suffix = s[l:]
		}
	} else {
		suffix = s
	}
	switch suffix {
	case "Forward":
		return DirectionForward, nil
	case "Backward":
		return DirectionBackward, nil
	}
	return Direction(0), errors.New("String does not correspond to any existing Direction values")
}
