package theme

const (
	BUTTON       = "button"
	CHECKBOX     = "checkbox"
	BACKGROUND   = "background"
	IMAGE        = "image"
	LABEL        = "label"
	MENUBAR      = "menubar"
	MENUITEM     = "menuitem"
	MENUDROPDOWN = "menudropdown"
	PANEL        = "panel"
	STATUSBAR    = "statusbar"
	TRACKBAR     = "trackbar"
)

const (
	STYLE_BUTTON                      = "style_button"
	STYLE_BUTTON_HOVERED              = "style_button_hovered"
	STYLE_BUTTON_FOCUSED              = "style_button_focused"
	STYLE_BUTTON_FOCUSEDHOVERED       = "style_button_focusedhovered"
	STYLE_BUTTON_DOWN                 = "style_button_down"
	STYLE_CHECKBOX                    = "style_checkbox"
	STYLE_CHECKBOX_HOVERED            = "style_checkbox_hovered"
	STYLE_CHECKBOX_FOCUSED            = "style_checkbox_focused"
	STYLE_CHECKBOX_FOCUSEDHOVERED     = "style_checkbox_focusedhovered"
	STYLE_BACKGROUND                  = "style_background"
	STYLE_IMAGE_BACKGROUND            = "style_image_background"
	STYLE_LABEL                       = "style_label"
	STYLE_MENUBAR                     = "style_menubar"
	STYLE_MENUBAR_HOVERED             = "style_menubar_hovered"
	STYLE_MENUBAR_FOCUSED             = "style_menubar_focused"
	STYLE_MENUBAR_FOCUSEDHOVERED      = "style_menubar_focusedhovered"
	STYLE_MENUITEM                    = "style_menuitem"
	STYLE_MENUITEM_HOVERED            = "style_menuitem_hovered"
	STYLE_MENUITEM_FOCUSED            = "style_menuitem_focused"
	STYLE_MENUITEM_FOCUSEDHOVERED     = "style_menuitem_focusedhovered"
	STYLE_MENUDROPDOWN                = "style_menudropdown"
	STYLE_MENUDROPDOWN_HOVERED        = "style_menudropdown_hovered"
	STYLE_MENUDROPDOWN_FOCUSED        = "style_menudropdown_focused"
	STYLE_MENUDROPDOWN_FOCUSEDGROUP   = "style_menudropdown_focusedgroup"
	STYLE_MENUDROPDOWN_FOCUSEDHOVERED = "style_menudropdown_focusedhovered"
	STYLE_MINIMIZINGBAR               = "style_minimizingbar"
	STYLE_PANEL                       = "style_panel"
	STYLE_PANEL_HOVERED               = "style_panel_hovered"
	STYLE_PANEL_FOCUSED               = "style_panel_focused"
	STYLE_PANEL_FOCUSEDHOVERED        = "style_panel_focusedhovered"
	STYLE_STATUSBAR                   = "style_statusbar"
	STYLE_TRACKBAR                    = "style_trackbar"
	STYLE_TRACKBAR_HOVERED            = "style_trackbar_hovered"
	STYLE_TRACKBAR_FOCUSED            = "style_trackbar_focused"
	STYLE_TRACKBAR_FOCUSEDHOVERED     = "style_trackbar_focusedhovered"
)

const (
	BUTTON_FRAME                = "button_frame"
	CHECKBOX_CHECKED            = "checkbox_checked"
	CHECKBOX_NOTCHECKED         = "checkbox_notchecked"
	BACKGROUND_PATTERN          = "background_pattern"
	IMAGE_BACKGROUND            = "image_background"
	MENUBAR_FIRST_ITEM_POSITION = "menubar_first_item_position"
	MENUBAR_SPACE_BETWEEN_ITEMS = "menubar_space_between_items"
	MENUDROPDOWN_FRAME          = "menudropdown_frame"
	MINIMIZINGBAR_STICKER_WIDTH = "minimizingbar_sticker_width"
	MINIMIZING_CLICK_WIDTH      = "minimizingbar_click_width"
	PANEL_FRAME                 = "panel_frame"
	STATUSBAR_ITEMS_SEPARATOR   = "statusbar_items_separator"
	SHADOW_ENABLED              = "shadow_enabled"
	SHADOW_VALUE                = "shadow_value"
	SHADOW_VERTICAL_OFFSET      = "shadow_vertical_offset"
	SHADOW_HORIZONTAL_OFFSET    = "shadow_horizontal_offset"
	TRACKBAR_BACKGROUND         = "tackbar_background"
	TRACKBAR_CURSOR             = "tackbar_cursor"
)
