color_P0: "#000F1C"
color_P1: "#081827"
color_P2: "#102231"
color_P3: "#182B3C"
color_P4: "#213446"
color_P5: "#293D51"
color_P6: "#31475B"
color_P7: "#395066"
color_P8: "#415970"
color_P9: "#4D6984"
color_P10: "#587A99"
color_P11: "#648AAD"
color_P12: "#709AC2"
color_P13: "#7CAAD6"
color_P14: "#87BBEB"
color_P15: "#93CBFF"
color_S0: "#100700"
color_S1: "#2E1300"
color_S2: "#4C1F00"
color_S3: "#6A2B00"
color_S4: "#883700"
color_S5: "#A54200"
color_S6: "#C34E00"
color_S7: "#E15A00"
color_S8: "#FF6600"
color_S9: "#FF781E"
color_S10: "#FF8B3D"
color_S11: "#FF9D5B"
color_S12: "#FFAF7A"
color_S13: "#FFC198"
color_S14: "#FFD4B7"
color_S15: "#FFE6D5"
color_BL: "#000000"
color_WH: "#FFFFFF"
color_G0: "#000000"
color_G1: "#111111"
color_G2: "#222222"
color_G3: "#333333"
color_G4: "#444444"
color_G5: "#555555"
color_G6: "#666666"
color_G7: "#777777"
color_G8: "#888888"
color_G9: "#999999"
color_G10: "#AAAAAA"
color_G11: "#BBBBBB"
color_G12: "#CCCCCC"
color_G13: "#DDDDDD"
color_G14: "#EEEEEE"
color_G15: "#FFFFFF"
color_g0: "#001D23"
color_g1: "#1B383E"
color_g2: "#355359"
color_g3: "#506E74"
color_g4: "#6A888E"
color_g5: "#85A3A9"
color_g6: "#9FBEC4"
color_g7: "#BAD9DF"
style_button: "P1,P4"
style_button_hovered: "P2,P9"
style_button_focused: "S2,S9"
style_button_focusedhovered: "S2,S12"
style_button_down: "S12,S2"
style_checkbox: "P0,P4"
style_checkbox_hovered: "P0,P6"
style_checkbox_focused: "S0,S4"
style_checkbox_focusedhovered: "S0,S6"
style_background: "P8,0"
style_image_background: "$1,TRANSPARENT"
style_label: "#76b5c5,TRANSPARENT"
style_menubar: "P2,P9"
style_menubar_hovered: "P2,P9"
style_menubar_focused: "P2,P9"
style_menubar_focusedhovered: "P2,P9"
style_menuitem: "P2,P9"
style_menuitem_hovered: "P2,P9"
style_menuitem_focused: "P2,P9"
style_menuitem_focusedhovered: "P14,P2"
style_menudropdown: "P2,P9"
style_menudropdown_hovered: "P2,P9"
style_menudropdown_focused: "P2,P9"
style_menudropdown_focusedgroup: "P2,P9"
style_minimizingbar: "#f4dc6280,#f4dc6280"
style_panel: "P0,P3"
style_panel_hovered: "P0,P7"
style_panel_focused: "S2,S5"
style_panel_focusedhovered: "S2,S10"
style_statusbar: "P4,P7"
style_trackbar: "P4,P7"
style_trackbar_hovered: "P1,P5"
style_trackbar_focused: "S5,S7"
style_trackbar_focusedhovered: "S1,S6"
button_frame: 7
checkbox_notchecked: "☐ "
checkbox_checked: "🗹 "
background_pattern: '●'
image_background: '░'
menubar_first_item_position: 2
menubar_space_between_items: 3
menudropdown_frame: 7
minimizingbar_sticker_width: 30
minimizingbar_click_width: 10
panel_frame: 6
statusbar_items_separator: " | "
trackbar_cursor: '▼'
trackbar_background: '-'
shadow_enabled: true
shadow_value: uint8(120)
shadow_vertical_offset: 1
shadow_horizontal_offset: 2